//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LepardCab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int DriverId { get; set; }
        public string RideStart { get; set; }
        public string RideEnd { get; set; }
        public decimal Fare { get; set; }
        public string StartLatitute { get; set; }
        public string StartLongitute { get; set; }
        public string EndLatitute { get; set; }
        public string EndLongitute { get; set; }
    
        public virtual User User { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
